version: 2.1
orbs:
  ship: auth0/ship@0.1.0
parameters:
  docker_image:
    type: string
    default: circleci/node:12-browsers
jobs:
  build:
    docker:
      - image: << pipeline.parameters.docker_image >>
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "package-lock.json" }}
      - run: npm ci
      - save_cache:
          key: dependencies-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run: npm run lint
      - run: npm run build:prod
      - run: npm run test:ci
      - run:
          name: Upload coverage
          command: ./node_modules/.bin/codecov
      - store_artifacts:
          path: projects/playground/e2e/videos
      - store_artifacts:
          path: projects/playground/e2e/screenshots
      - store_test_results:
          path: projects/playground/test-results
      - store_test_results:
          path: projects/auth0-angular/test-results
  browserstack:
    docker:
      - image: << pipeline.parameters.docker_image >>
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm ci
      - restore_cache:
          key: dependencies-{{ checksum "package-lock.json" }}
      - run: npx concurrently --raw --kill-others --success first "npm:start:local" "wait-on http://127.0.0.1:4200/ && browserstack-cypress run --build-name $CIRCLE_BRANCH"
workflows:
  build_and_test:
    jobs:
      - build
      - browserstack:
          requires:
            - build
          context:
            - browserstack-env
      - ship/node-publish:
          requires:
            - browserstack
          context:
            - publish-npm
            - publish-gh
          filters:
            branches:
              only:
                - master
